// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYrqsE8mI3MucqJS-O4zg_Euxm-RUO9dA',
    appId: '1:342714257588:web:29a289b14b6ac9357c07e1',
    messagingSenderId: '342714257588',
    projectId: 'appstore-b6e0f',
    authDomain: 'appstore-b6e0f.firebaseapp.com',
    storageBucket: 'appstore-b6e0f.appspot.com',
    measurementId: 'G-XPRSRYEXT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHSywYRL6oxbJBA6tIaRTZJSFnWzfrCCU',
    appId: '1:342714257588:android:84ce16e146dac6fa7c07e1',
    messagingSenderId: '342714257588',
    projectId: 'appstore-b6e0f',
    storageBucket: 'appstore-b6e0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU-9e9U9UskoL3_I4BTFwMnl__Bp73xrE',
    appId: '1:342714257588:ios:825a02be080558237c07e1',
    messagingSenderId: '342714257588',
    projectId: 'appstore-b6e0f',
    storageBucket: 'appstore-b6e0f.appspot.com',
    iosBundleId: 'com.riccardodebellini.appstore.appStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU-9e9U9UskoL3_I4BTFwMnl__Bp73xrE',
    appId: '1:342714257588:ios:825a02be080558237c07e1',
    messagingSenderId: '342714257588',
    projectId: 'appstore-b6e0f',
    storageBucket: 'appstore-b6e0f.appspot.com',
    iosBundleId: 'com.riccardodebellini.appstore.appStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYrqsE8mI3MucqJS-O4zg_Euxm-RUO9dA',
    appId: '1:342714257588:web:3da92d5deed386d97c07e1',
    messagingSenderId: '342714257588',
    projectId: 'appstore-b6e0f',
    authDomain: 'appstore-b6e0f.firebaseapp.com',
    storageBucket: 'appstore-b6e0f.appspot.com',
    measurementId: 'G-3H6RYBYRV5',
  );
}
